---
- hosts: nginx_server
  sudo: yes
  remote_user: abhi
  vars:
    http_port: 80
  remote_user: abhi
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=latest update_cache=true
      notify:
        - start nginx
    - name: ensure cache is updated
      apt: pkg=apache2 state=installed update_cache=true

    - name: Upload default index.html for host
      copy: src=/home/abhi/static_files/nginx/index.html dest=/usr/share/nginx/html mode=0644
      notify:
      - restart nginx
    - name: ensure nginx is running 
      service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

- hosts: apache_server
  sudo: yes
  vars:
    http_port: 80
    max_clients: 200
  remote_user: abhi
  tasks:
  - name: ensure apache is at the latest version
    apt: pkg=apache2 state=latest update_cache=true
  - name: ensure cache is updated
    apt: pkg=apache2 state=installed update_cache=true
  - name: replace default index.html file
    copy: src=/home/abhi/static_files/apache/index.html dest=/var/www/html/ mode=0644
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started 
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted 
